/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyLib */

#ifndef _Included_MyLib
#define _Included_MyLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyLib
 * Method:    mainFunc
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MyLib_mainFunc
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
